name: Apply Comic Book Discounts

on:
  schedule:
    # Run every Sunday at 2 AM MST (9 AM UTC)
    - cron: '0 9 * * 0'
  
  # Allow manual trigger from GitHub Actions tab
  workflow_dispatch:

jobs:
  apply-discounts:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Apply discounts to aged comics
        env:
          LIGHTSPEED_API_KEY: ${{ secrets.LIGHTSPEED_API_KEY }}
          LIGHTSPEED_ACCOUNT_ID: ${{ secrets.LIGHTSPEED_ACCOUNT_ID }}
          TAG_PREFIX: "new release-"
          CLEARANCE_PRICE_NAME: "Comics Clearance - 20% Off"
          DISCOUNT_DAYS: "14"
          DISCOUNT_PERCENT: "0.20"
        run: |
          python src/discount_manager.py
      
      - name: Upload run logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: discount-logs-${{ github.run_number }}
          path: |
            *.log
          retention-days: 30
